ALTER TABLE overlay_settings
  ADD COLUMN ms_enabled                BOOLEAN      NOT NULL DEFAULT true,
  ADD COLUMN ms_yt_shorts              BOOLEAN      NOT NULL DEFAULT true,
  ADD COLUMN ms_tiktok                 BOOLEAN      NOT NULL DEFAULT true,
  ADD COLUMN ms_ig_reels               BOOLEAN      NOT NULL DEFAULT true,
  ADD COLUMN ms_voice_note             BOOLEAN      NOT NULL DEFAULT false,
  ADD COLUMN ms_max_video_duration     INTEGER      NOT NULL DEFAULT 300,
  ADD COLUMN ms_price_per_second_video BIGINT       NOT NULL DEFAULT 100,
  ADD COLUMN ms_max_audio_duration     INTEGER      NOT NULL DEFAULT 60,
  ADD COLUMN ms_price_per_second_audio BIGINT       NOT NULL DEFAULT 5000,
  ADD COLUMN ms_min_audio              BIGINT       NOT NULL DEFAULT 50000,
  ADD COLUMN ms_background_color       VARCHAR(20),
  ADD COLUMN ms_highlight_color        VARCHAR(20),
  ADD COLUMN ms_text_color             VARCHAR(20),
  ADD COLUMN ms_template_text          TEXT         NOT NULL DEFAULT 'baru saja memberi',
  ADD COLUMN ms_no_border              BOOLEAN      NOT NULL DEFAULT false,
  ADD COLUMN ms_font_weight            INTEGER      NOT NULL DEFAULT 500,
  ADD COLUMN ms_font_family            VARCHAR(50)  NOT NULL DEFAULT 'Poppins',
  ADD COLUMN ms_show_nsfw              BOOLEAN      NOT NULL DEFAULT false;
