ALTER TABLE overlay_settings
    ADD COLUMN IF NOT EXISTS sub_initial_hours   INTEGER NOT NULL DEFAULT 10,
    ADD COLUMN IF NOT EXISTS sub_initial_minutes INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS sub_initial_seconds INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS sub_no_border       BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS sub_bg_color        TEXT    NOT NULL DEFAULT '#faae2b',
    ADD COLUMN IF NOT EXISTS sub_auto_play       BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS sub_text_color      TEXT    NOT NULL DEFAULT '#111111',
    ADD COLUMN IF NOT EXISTS sub_font_weight     INTEGER NOT NULL DEFAULT 500,
    ADD COLUMN IF NOT EXISTS sub_font_content    TEXT    NOT NULL DEFAULT 'default',
    ADD COLUMN IF NOT EXISTS sub_time_rules      JSONB   NOT NULL DEFAULT '[]';
