ALTER TABLE overlay_settings
    ADD COLUMN IF NOT EXISTS lb_title        TEXT    NOT NULL DEFAULT 'Leaderboard',
    ADD COLUMN IF NOT EXISTS lb_bg_color     TEXT    NOT NULL DEFAULT '#faae2b',
    ADD COLUMN IF NOT EXISTS lb_text_color   TEXT    NOT NULL DEFAULT '#333333',
    ADD COLUMN IF NOT EXISTS lb_font_weight  INTEGER NOT NULL DEFAULT 500,
    ADD COLUMN IF NOT EXISTS lb_no_border    BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS lb_hide_amount  BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS lb_font_title   TEXT    NOT NULL DEFAULT 'default',
    ADD COLUMN IF NOT EXISTS lb_font_content TEXT    NOT NULL DEFAULT 'default',
    ADD COLUMN IF NOT EXISTS lb_time_range   TEXT    NOT NULL DEFAULT 'all',
    ADD COLUMN IF NOT EXISTS lb_limit        INTEGER NOT NULL DEFAULT 10;
